### ISSUE TITLE
Does not work unless it is a string

### ISSUE THREAD

**Issue by grokky1** [jrockwood/MakeBddName#1]
Using latest version of VS2017 and the extension.

If the select contains `"foo bar baz"` then the extension works as expected.

But if the selection is not a string, e.g. `foo bar baz` then it does not work. It doesn't get transformed.

**Comment by jrockwood** [comment]
Cool, thanks for reporting. I'll take a look.

**Comment by jrockwood** [comment]
Updated new version 1.3.2 to the Visual Studio gallery (https://marketplace.visualstudio.com/items?itemName=JustinRockwood.MakeBDDName). Visual Studio should prompt you to update.
