### ISSUE TITLE
Make logging optional

### ISSUE THREAD

**Issue by grokky1** [jrockwood/MakeBddName#2]
Every time the extension works, it writes to its section of the output window.

This is completely unnecessary to a user of the extension. Perhaps allow us to disable it via a toggle in the configuration panel.

**Comment by jrockwood** [comment]
Thanks for reporting this - I must have left some logging on by accident. I'll turn off the logging, because I agree that's annoying.

**Comment by jrockwood** [comment]
Updated new version 1.3.2 to the Visual Studio gallery (https://marketplace.visualstudio.com/items?itemName=JustinRockwood.MakeBDDName). Visual Studio should prompt you to update.
